### ISSUE TITLE
Invalid backend response. Data is not JSON.

### ISSUE THREAD

**Issue by quantumgraphics** [lyrasoft/remoteimage#77] opened 2016-10-25 09:45 UTC
Database Version    5.6.33-cll-lve
Database Collation  utf8mb4_general_ci
Database Connection Collation   utf8mb4_general_ci
PHP Version 7.0.12
Web Server  Apache
WebServer to PHP Interface  cgi-fcgi
Joomla! Version Joomla! 3.6.3 Stable [ Noether ] 17-October-2016 13:35 GMT

**Comment by asika32764** [comment] 2016-10-25 12:19
Could you try install ARI in a new Joomla to test that is plugin conflict or not?

**Comment by quantumgraphics** [comment] 2016-10-26 11:06
It is a fresh Joomla install

**Comment by Mosolyalbum** [comment] 2017-04-10 12:28
Hy,
I've got the same error when I try to open media manager. It worked before, but I don't know what had been changed!
Joomla version: 3.6.4.
PHP 5.6.23
MySQL 5.6.35

Thanks.

**Comment by asika32764** [comment] 2017-04-10 13:06
This is usually caused by a 3rd party plugin conflict, could you try install ARI in a new pure Joomla to test?

If it works, then you must disable every plugins to check which is the reason to make this problem.

**Comment by Mosolyalbum** [comment] 2017-04-11 07:03
Thank you, 
I've found the problematic plugin: Advanced Module Manager 
I don't understand, they were worked together in the last 3 years.

**Comment by asika32764** [comment] 2017-04-11 08:41
I'm not sure, maybe some php warning message appeared to broke the JSON string, every plugin with wrong syntax might caused this problem.

Try upgrade  Advanced Module Manager. If you know how to use Chrome development tools, just upload the Network response and console screenshot.

**Comment by quantumgraphics** [comment] 2017-04-11 11:44
I found turning error reporting off solved this issue in most cases.

**Comment by Mosolyalbum** [comment] 2017-04-11 12:58
Thanks,
Error reporting is off in my case.
I'm going to upgrade Advanced Module Manager. I've found it had been modified, but can't be upgrade from the version I have, so I need to reinstall it. Maybe that'll be the solution...

**Comment by asika32764** [comment] 2017-04-11 13:02
Close as the issue was caused by 3rd party extension.

The Ajax JSON must be complete that Javascript can parse it, so it cannot fixed by RemoteImage or any frontend side.

**Closed by asika32764** 2017-04-11 13:02 UTC
