### ISSUE TITLE
Remoteimage not replacing Joomla media manager since 3.4.5

### ISSUE THREAD

**Issue by tgetgood13** [lyrasoft/remoteimage#64] opened 2015-11-05 13:37 UTC
Hi,

After installing Joomla 3.4.5 I received the error using Remoteimage 2.0.2. Since updating this to 2.0.5 the sync between media manager and Remoteimage seems to be missing.

Am unsure if this is a bug or whether some form of config got wiped (although not sure what that could be) due to the compatibility issues.

It may be relevant to note that we are using JCE (2.5.11).

Cheers,
Tom

**Comment by webjive** [comment] 2015-11-06 20:14
Yep, ever since 3.4.4 their have been some bugs. We had to remove it from most of our installs. The product doesn't seem to be supported anymore. Shame, its an AWESOME image manager replacement for Joomla.

**Comment by Gerlof** [comment] 2015-11-26 10:44
I read you are using RemoteImage 2.02.
Do you still experience errors after installation of version2.05?

**Comment by webjive** [comment] 2015-11-26 10:45
Running 2.05 myself

**Comment by tgetgood13** [comment] 2015-11-26 12:01
I am not experiencing errors using 2.05, it just doesn't work the same way it did before.
It does not replace the media manager via JCE or the 'Images and Links' tab in Joomla content.

**Comment by Gerlof** [comment] 2015-12-02 11:17
Did you check the options in tab [Integrate]?
See image attached: 
![remote-image-manager-integrate](https://cloud.githubusercontent.com/assets/3882884/11529643/b209612e-98ee-11e5-929b-50d42897c097.jpg)

**Comment by tgetgood13** [comment] 2015-12-02 11:36
Yes, config is identical to that.

**Comment by Gerlof** [comment] 2015-12-02 12:52
Maybe the problem is caused by JCE? See the change in version 2.5.5 (https://www.joomlacontenteditor.net/support/releases/changelog/editor): "Added: All fields of type "media" will now open the JCE File Browser instead of the Joomla Media Manager. This can be reverted by disabling the System - JCE plugin in the Joomla Extension Manager."

You can try if disabling plugin System - JCE plugin will solve the problem you experience.

**Comment by asika32764** [comment] 2015-12-07 07:40
I tried ARI in 3.4.5 with no problem. I think maybe it caused by some conflict with other plugins.

See Animation

![media-ari](https://cloud.githubusercontent.com/assets/1639206/11621594/c7e188ce-9cf8-11e5-922b-64315ec175d5.gif)

**Comment by asika32764** [comment] 2015-12-07 07:45
Also works well with JCE 2.5.11

![151207-0001](https://cloud.githubusercontent.com/assets/1639206/11621673/91ab16ac-9cf9-11e5-8112-367683906785.jpg)

**Comment by numinousmedia** [comment] 2015-12-09 19:55
I'm experiencing a similar issue with the latest version of Asikart Remote Image in Joomla 3.4.5. When I attempt to open it, my site gives me a 404 error. If I disable the integration in its settings, I can open the component, but it returns an "Unable to Connect to Backend" error.

**Comment by tyfairclough** [comment] 2016-06-08 13:22
This issue appears to have re-occurred in Joomla 3.5.1 :(

**Comment by asika32764** [comment] 2016-06-08 13:49
Could anyone who meet this problem please try to install ARI in a new empty Joomla with same server environment?

I need more information to detect the reason and check that it id not a plugins conflict, since I still cannot reproduce the issue.

**Comment by tyfairclough** [comment] 2016-06-08 13:51
Yea I should be able to do that for you. I just got a new sitegrounds
account so have a domain with nothing on it.

On Wed, Jun 8, 2016 at 2:49 PM, Simon Asika <notifications@github.com>
wrote:

> Could anyone who meet this problem please try to install ARI in a new
> empty Joomla with same server environment?
>
> I need more information to detect the reason and check that it id not a
> plugins conflict, since I still cannot reproduce the issue.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/lyrasoft/remoteimage/issues/64#issuecomment-224594473>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABnTCfytBTtMN47zE42_OZ_uSWxdlC3mks5qJsh4gaJpZM4Gcmsn>
> .
>



-- 

--------------------------------

www.tyfairclough.com
ty@tyfairclough.com

+44(0) 7455 747 787

104a Main Road
Chelmsford
Essex
CM1 7AE

**Comment by asika32764** [comment] 2016-06-08 13:53
Thank you, if you still get the same error, could you please send me an admin account that I can test it?

asika32764 [at] gmail.com

Thank you

**Comment by tyfairclough** [comment] 2016-06-08 14:05
The fresh install does not have the issue. So it appears to work.

I logged in and out with to resolve the issue on 3.5.1 on my production
site running various plugins etc.

All is right with the world once more...

Thanks :D

On Wed, Jun 8, 2016 at 2:53 PM, Simon Asika <notifications@github.com>
wrote:

> Thank you, if you still get the same error, could you please send me an
> admin account that I can test it?
>
> asika32764 [at] gmail.com
>
> Thank you
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/lyrasoft/remoteimage/issues/64#issuecomment-224595631>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABnTCX9k4RpwPO16qtN7EqCxR_vb37TPks5qJslRgaJpZM4Gcmsn>
> .
>



-- 

--------------------------------

www.tyfairclough.com
ty@tyfairclough.com

+44(0) 7455 747 787

104a Main Road
Chelmsford
Essex
CM1 7AE

**Comment by asika32764** [comment] 2016-06-08 16:26
So maybe you can try to close some plugin to check which is the reason caused this issue, that I can know how to get rid of the same problem.

The similar issue occurred on Akeeba in the past, Akeeba plugins crashed my all components, after we catch the reason, we can fix it.

See
- https://github.com/lyrasoft/quickicons/issues/5#issuecomment-51447878
- https://www.akeebabackup.com/support/admin-tools/20693-geo-ip-plugin-conflict-with-asikart.html

**Comment by tyfairclough** [comment] 2016-06-08 16:28
Ah I'm running akeeba backup pro and admin tools. Maybe that has had an
impact.

On Wed, Jun 8, 2016 at 5:26 PM, Simon Asika <notifications@github.com>
wrote:

> So maybe you can try to close some plugin to check which is the reason
> caused this issue, that I can know how to get rid of the same problem.
>
> The similar issue occurred on Akeeba in the past, Akeeba plugins crashed
> my all components, after we catch the reason, we can fix it.
>
> See
>
>    - lyrasoft/quickicons#5 (comment)
>    <https://github.com/lyrasoft/quickicons/issues/5#issuecomment-51447878>
>    -
>    https://www.akeebabackup.com/support/admin-tools/20693-geo-ip-plugin-conflict-with-asikart.html
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/lyrasoft/remoteimage/issues/64#issuecomment-224646711>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABnTCasgnsI0d5Vk4UR-CXh9--CqLZTtks5qJu1MgaJpZM4Gcmsn>
> .
>



-- 

--------------------------------

www.tyfairclough.com
ty@tyfairclough.com

+44(0) 7455 747 787

104a Main Road
Chelmsford
Essex
CM1 7AE

**Comment by asika32764** [comment] 2016-06-08 16:30
That is an old issue, maybe not affected by akeeba now.

**Comment by asika32764** [comment] 2017-04-11 13:10
Closed as no new reaction of this issue.

**Closed by asika32764** 2017-04-11 13:10 UTC
