### ISSUE TITLE
Upgrade to 2.0.5 - No uploads anymore allowed

### ISSUE THREAD

**Issue by ppan2015** [lyrasoft/remoteimage#65] opened 2015-11-11 15:11 UTC
Upgrade to 2.0.5
now I cannot upload any image file anymore, causing the error message "Upload Error. No file for upload found."

Working on Jooma 3.4.5.

**Comment by asika32764** [comment] 2015-12-07 08:01
Hi, I can't reproduce this issue in a new Joomla 3.4.5 site with 2.0.5.

Please check there is no any conflict with other plugins.

(Maybe try reinstall ARI on a new site, or close some other plugins to test)

**Comment by asika32764** [comment] 2017-04-11 13:09
Closed as no new comments.

**Closed by asika32764** 2017-04-11 13:09 UTC
